import{a as w,S,i as u}from"./assets/vendor-BgmC94F3.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const q="53054234-db08f1651f6ed2d5abc76426b",v="https://pixabay.com/api/",M=w.create({baseURL:v,timeout:1e4});async function E(e,o=1){return(await M.get("",{params:{key:q,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data}let a=null;function I(){return a||(a=new S(".gallery a",{captionsData:"alt",captionDelay:250})),a}function $(e){const o=document.querySelector(".gallery"),s=e.map(n=>`
      <li class="gallery-item">
        <a href="${n.largeImageURL}">
          <img src="${n.webformatURL}" alt="${n.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${n.likes}</p>
          <p><b>Views</b> ${n.views}</p>
          <p><b>Comments</b> ${n.comments}</p>
          <p><b>Downloads</b> ${n.downloads}</p>
        </div>
      </li>`).join("");o.insertAdjacentHTML("beforeend",s),a&&a.refresh()}function p(){const e=document.querySelector(".gallery");e.innerHTML=""}function B(){const e=document.querySelector(".loader");e&&e.classList.add("visible")}function P(){const e=document.querySelector(".loader");e&&e.classList.remove("visible")}const c=document.querySelector(".load-more"),l=document.querySelector(".end-message");function R(){c&&c.classList.remove("is-hidden")}function h(){c&&c.classList.add("is-hidden")}function x(){l&&l.classList.remove("is-hidden")}function L(){l&&l.classList.add("is-hidden")}const m=document.querySelector(".form"),O=document.querySelector('input[name="search-text"]'),C=document.querySelector(".gallery"),y=document.querySelector(".load-more");document.querySelector(".loader");document.querySelector(".end-message");const H=15;let f="",i=1,g=0;I();function A(){const e=C.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}async function b(){B(),L(),h();try{const e=await E(f,i);g=e.totalHits;const o=e.hits;if(o.length===0){u.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),p();return}$(o),i*H>=g?x():R(),i>1&&A()}catch(e){u.error({message:`Error fetching images: ${e.message}`,position:"topRight"})}finally{P()}}async function D(e){e.preventDefault();const o=O.value.trim();if(o===""){u.warning({message:"Please enter a search term.",position:"topRight"});return}o!==f&&(f=o,i=1,p(),L(),await b())}async function U(){i+=1,h(),await b()}m&&m.addEventListener("submit",D);y&&y.addEventListener("click",U);
//# sourceMappingURL=index.js.map
