import{a as v,S as q,i as n}from"./assets/vendor-BgmC94F3.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))f(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const h of o.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&f(h)}).observe(document,{childList:!0,subtree:!0});function l(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function f(t){if(t.ep)return;t.ep=!0;const o=l(t);fetch(t.href,o)}})();const x="53054234-db08f1651f6ed2d5abc76426b",R="https://pixabay.com/api/",A=v.create({baseURL:R,timeout:1e4});async function m(e,r=1){return(await A.get("",{params:{key:x,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}function g(e){const r=document.querySelector(".gallery"),l=e.map(t=>`
      <li class="gallery-item">
        <a href="${t.largeImageURL}">
          <img src="${t.webformatURL}" alt="${t.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${t.likes}</p>
          <p><b>Views</b> ${t.views}</p>
          <p><b>Comments</b> ${t.comments}</p>
          <p><b>Downloads</b> ${t.downloads}</p>
        </div>
      </li>`).join("");r.insertAdjacentHTML("beforeend",l),new q(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}function M(){const e=document.querySelector(".gallery");e.innerHTML=""}function b(){const e=document.querySelector(".loader");e&&e.classList.add("visible")}function L(){const e=document.querySelector(".loader");e&&e.classList.remove("visible")}const p=document.querySelector(".form"),y=document.querySelector('input[name="search-text"]'),d=document.querySelector(".gallery"),i=document.querySelector(".load-more"),P=document.querySelector(".loader");(!p||!y||!d||!P)&&console.error('Missing required DOM elements. Check that .form, input[name="search-text"], .gallery and .loader exist in index.html');let a="",c=1,u=0;const w=15;p&&p.addEventListener("submit",E);i&&i.addEventListener("click",B);async function E(e){if(e.preventDefault(),!!y){if(a=y.value.trim(),!a){n.warning({message:"Please enter a search query!",position:"topRight"});return}c=1,u=0,M(),s(),b();try{const r=await m(a,c);if(!r||!Array.isArray(r.hits))throw new Error("Unexpected API response");if(r.hits.length===0){n.info({message:"No images found for your request.",position:"topRight"}),s();return}g(r.hits),u=r.totalHits||0,u>w?S():(s(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(r){console.error("Search error:",r),n.error({message:"Something went wrong! Try again later.",position:"topRight"})}finally{L()}}}async function B(){if(a){c+=1,b(),s();try{const e=await m(a,c);if(!e||!Array.isArray(e.hits))throw new Error("Unexpected API response");if(e.hits.length===0){n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),s();return}g(e.hits),I(),c*w>=u?(s(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):S()}catch(e){console.error("Load more error:",e),n.error({message:"Something went wrong! Try again later.",position:"topRight"})}finally{L()}}}function S(){i&&i.classList.remove("is-hidden")}function s(){i&&i.classList.add("is-hidden")}function I(){if(!d)return;const e=d.querySelector(".photo-card")||d.firstElementChild;if(!e)return;const{height:r}=e.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
