import{a as x,S as M,i as d}from"./assets/vendor-BgmC94F3.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))m(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const h of o.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&m(h)}).observe(document,{childList:!0,subtree:!0});function l(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function m(t){if(t.ep)return;t.ep=!0;const o=l(t);fetch(t.href,o)}})();const A="53054234-db08f1651f6ed2d5abc76426b",E="https://pixabay.com/api/",P=x.create({baseURL:E,timeout:1e4});async function L(e,r=1){return(await P.get("",{params:{key:A,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}function b(e){const r=document.querySelector(".gallery"),l=e.map(t=>`
      <li class="gallery-item">
        <a href="${t.largeImageURL}">
          <img src="${t.webformatURL}" alt="${t.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${t.likes}</p>
          <p><b>Views</b> ${t.views}</p>
          <p><b>Comments</b> ${t.comments}</p>
          <p><b>Downloads</b> ${t.downloads}</p>
        </div>
      </li>`).join("");r.insertAdjacentHTML("beforeend",l),new M(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}function R(){const e=document.querySelector(".gallery");e.innerHTML=""}function w(){const e=document.querySelector(".loader");e&&e.classList.add("visible")}function S(){const e=document.querySelector(".loader");e&&e.classList.remove("visible")}const p=document.querySelector(".form"),y=document.querySelector('input[name="search-text"]'),u=document.querySelector(".gallery"),n=document.querySelector(".load-more"),B=document.querySelector(".loader"),c=document.querySelector(".end-message");(!p||!y||!u||!B||!n||!c)&&console.error('Missing required DOM elements. Check that .form, input[name="search-text"], .gallery, .loader, .load-more and .end-message exist in index.html');let i="",a=1,f=0;const q=15;p&&p.addEventListener("submit",I);n&&n.addEventListener("click",O);async function I(e){if(e.preventDefault(),!!y){if(i=y.value.trim(),!i){d.warning({message:"Please enter a search query!",position:"topRight"});return}a=1,f=0,R(),s(),$(),w();try{const r=await L(i,a);if(!r||!Array.isArray(r.hits))throw new Error("Unexpected API response");if(r.hits.length===0){d.info({message:"No images found for your request.",position:"topRight"}),s();return}b(r.hits),f=r.totalHits||0,f>q?v():(s(),g())}catch(r){console.error("Search error:",r),d.error({message:"Something went wrong! Try again later.",position:"topRight"})}finally{S()}}}async function O(){if(i){a+=1,w(),s();try{const e=await L(i,a);if(!e||!Array.isArray(e.hits))throw new Error("Unexpected API response");if(e.hits.length===0){g(),s();return}b(e.hits),U(),a*q>=f?(s(),g()):v()}catch(e){console.error("Load more error:",e),d.error({message:"Something went wrong! Try again later.",position:"topRight"})}finally{S()}}}function v(){n&&n.classList.remove("is-hidden")}function s(){n&&n.classList.add("is-hidden")}function g(){c&&c.classList.remove("is-hidden")}function $(){c&&c.classList.add("is-hidden")}function U(){if(!u)return;const e=u.querySelector(".photo-card")||u.firstElementChild;if(!e)return;const{height:r}=e.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
